myblog/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail,
        name='post_detail'
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSitemap


sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

myblog/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager

User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']), ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий от {self.name} на пост {self.post.title}'

myblog/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField(label='Запрос:')

myblog/blog/views.py
from django.conf import settings
from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404, render

from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Post


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')
    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts,
        }
    )


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{data["name"]} рекомендует тебе прочитать {post.title}'
            message = (f'Прочитай {post.title} по адресу: {post_url}\n\n '
                       f'{data["name"]} комментарии: {data["comments"]}')
            send_mail(subject, message, settings.EMAIL_ADMIN, [data['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return render(request, 'blog/post/comment.html',
                      {'post': post,
                       'form': form,
                       'comment': comment}
                      )


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query)
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

myblog/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>Мой блог</h2>
    <p>Всего постов: {% total_posts %}</p>
    <p>
      <a href="{% url 'blog:post_feed' %}">
        RSS-лента
      </a>
    </p>
    <h3>Последние посты</h3>
    {% show_latest_posts 3 %}
    <h3>Самые комментируемые посты</h3>
    {% get_most_commented_posts as most_commented_posts %}
    {% for post in most_commented_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% endfor %}
  </div>
</body>
</html>

myblog/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен</h2>
    <p><a href="{{ post.get_absolute_url }}">Назад к посту</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
  <script>
    // Функция для переадресации через указанное количество секунд
    function redirectToPostPage() {
      setTimeout(function() {
        window.location.href = "{{ post.get_absolute_url }}";
      }, 4000); // 4000 миллисекунд = 4 секунды
    }

    // Вызываем функцию при загрузке страницы
    redirectToPostPage();
  </script>
{% endblock %}

myblog/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Опубликовано: {{ post.publish }} автор: {{ post.author.username }}
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'blog:post_list' %}?page={{ request.session.page_number|default_if_none:'1' }}">
      <- вернутся к списку постов
    </a>
  </p>
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
      (づ｡◕‿‿◕｡)づ поделиться этим постом по почте
    </a>
  </p>
  {% if similar_posts %}
    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
    {% endfor %}
  {% else %}
    <h2>Похожих постов нет</h2>
  {% endif %}
  {% with comments.count as total_comments %}
   <p>
     Комментариев: {{ total_comments }}
   </p>
  {% endwith %}
  {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Комментарий {{ forloop.counter }} от {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
  {% empty %}
    <p>Комментариев нет.</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

myblog/blog/templates/blog/post/includes/comment_form.html
<h2>Добавьте новый комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
  {{ form.as_p }}
  {% csrf_token %}
  <p> <input type="submit" value="Добавить комментарий"></p>
</form>

myblog/blog/templates/blog/post/latest_post.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

myblog/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Бложе мой!{% endblock %}

{% block content %}
  <h1>Бложе мой!</h1>
  {% if tag %}
    <h2>Посты с тэгом:{{ tag.name }}</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    {% if post.tags.all %}
    <p class="tags">
      Теги:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    {% endif %}
    <p class="date">
      Опубликовано: {{ post.publish.date}} автор: {{ post.author.username }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

myblog/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
  {% if query %}
    <h1>Посты содержащие "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Найдено результатов: {{ total_results }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>Нет результатов по вашему запросу</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Искать снова</a></p>
  {% else %}
    <h1>Поиск по постам</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Поиск">
    </form>
  {% endif %}
{% endblock %}

myblog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Поделиться постом{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Письмо успешно отправлено</h1>
    <p>
      "{{ post.title }}" было успешно отправлено
      {{ form.cleaned_data.to }}
    </p>
  {% else %}
    <h1>Поделиться {{ post.title }} по почте</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

myblog/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
    {% endif %}
    <span class="current">
      Страница {{ page.number }} из {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Следующая</a>
    {% endif %}
  </span>
</div>